site_name: IT
repo_url: https://github.com/david2010/david2010.github.io
nav:
    - Digital Transformation: index.md
    - Data:
        - Data Strategy: data/datastrategy.md
        - Data Technology: data/datatechnology.md
    - DevOps: devops.md
    - Microservice(Design): microservice.md
    - Security: security.md
    - Programming:
        - powershell: dev/powershell.md
        - C#: dev/csharp.md
        - Summary: dev/compare.md
theme:
    name: mkdocs
    include_sidebar: false


